### ISSUE TITLE
Provide a update-goal parameter: add if missing

### ISSUE THREAD

**Issue by robbyb67** [mycila/license-maven-plugin#51] opened 2015-01-19 12:12 UTC
Suppose you have a year mentioned in your header and your project is long lasting which means the code is produced over years. 
If you change the year in your header, all files will be changed - not only the new ones. I understand this behaviour is needed in some use cases but is unwanted in the one described above.

**Comment by mathieucarbou** [comment] 2015-01-23 20:02
Yes I agree.
Please provide a pull request :-)

**Comment by mathieucarbou** [comment] 2016-04-25 18:04
duplicate of #81

**Closed by mathieucarbou** 2016-04-25 18:04 UTC
Labels: enhancement
