### ISSUE TITLE
-Dlicense.skip breaks Jacoco's report-aggregate in my multi module project

### ISSUE THREAD

**Issue by bbottema** [mycila/license-maven-plugin#161] opened 2019-12-09 14:01 UTC
Hi, first of all thanks for your hard work on this plugin, I use it very happily.

So what does the plugin actually do when the _license.skip_ property is passed from the command line? I'm getting some very weird behavior with Jacoco's aggregate reports.

Take [Simple Java Mail's](https://github.com/bbottema/simple-java-mail) commit 0d3c1fb16736ae512822e6a2528fea59f6596a32 (branch "junit-testing"), and first run:

`mvn clean verify -Dspotbugs.skip=true -Djavadoc.skip=true`

And then run:

`mvn clean verify -Dspotbugs.skip=true -Djavadoc.skip=true -Dlicense.skip=true`

And see that the very last step, Jacoco's aggregate goal fails with an exception about not being provided with original sources.

![image](https://user-images.githubusercontent.com/2115718/70441451-b4431a80-1a94-11ea-948b-d2d1e6654e9e.png)

I cannot think of any reason why skipping your plugin with that flag would cause this.

**Comment by mathieucarbou** [comment] 2020-06-25 16:23
Hi @bbottema ,
do you still have the issue ?

**Comment by mathieucarbou** [comment] 2020-08-19 00:56
closing since no feedback and no reproductible test given

**Closed by mathieucarbou** 2020-08-19 00:56 UTC
Labels: help, in-triage, old
